bitcoin-cash-node/bchnode-web

app/newsroom/bchn-flipstarted.html, app/templates/base.njk
This one should, according to Slack, not expire.
=> Update the Slack invite link

app/index.html, gulpfile.js, lang/en/index.yaml
A different take.
May contain formatting that isn't suitable for all devices - I have no means to properly test this.
=> Update front page with visions and objectives

app/download.html, app/index.html
What it says.
Please review.
NOTE: signatures links not yet working because the data has to be merged into the announcements repository
=> Update software release to 22.0.0

app/newsroom/Bitcoin-Cash-Node-2020-plans-for-May-upgrade-and-beyond.html, app/newsroom/index.html, blog/Bitcoin-Cash-Node-2020-plans-for-May-upgrade-and-beyond.md, scss/style.scss
=> [bounty] Add May 2020 upgrade article

app/data/newsroom.json, app/newsroom/Announcing-Bitcoin-Cash-Node-v22-0-0.html
This is a test bounty entry for an article in 
https://github.com/bitcoin-cash-node/bchnode-web/issues/66
=> [bounty] Add newsroom article for Announcing Bitcoin Cash Node v22.0.0

app/data/newsroom.json, blog/BCHN-Technical-Bulletin-2020-05-04.md
=> [bounty] Add "BCHN-Technical-Bulletin-2020-05-04" article

app/data/newsroom.json, blog/BCHN-FAQ-on-November-2020-Bitcoin-Cash-network-upgrade.md
=> [bounty] Add "BCHN FAQ on November 2020 Bitcoin Cash network upgrade" article

app/data/newsroom.json, blog/BCHN-announcement-regarding-Bitcoin-Cash-(BCH)-upgrade-specifications.md
=> [bounty] Add "BCHN announcement regarding Bitcoin Cash (BCH) upgrade specifications" article

app/data/newsroom.json, blog/BCHNv22版本发布公告.md
=> [bounty] Add "BCHN v22.0.0版本发布公告" article

app/data/newsroom.json, blog/Bitcoin-Cash-Node-Vision-and-Objectives.md
=> [bounty] Add "Bitcoin Cash Node: Vision and Objectives"

app/data/newsroom.json, blog/关于发布BCHN版本0-21-1的公告.md
=> [bounty] Add "关于发布BCHN版本0.21.1的公告" article

app/data/newsroom.json, blog/BCHN客户端关于BCH5月份升级的技术规范公告.md
=> [bounty] Add "BCHN客户端关于BCH5月份升级的技术规范公告" article

app/data/newsroom.json, blog/Anunciando-Bitcoin-Cash-Node-v0-21-1.md
=> [bounty] Add "Anunciando Bitcoin Cash Node v0.21.1" article

app/data/newsroom.json, blog/关于发布BCHN版本0-21-2的公告.md
=> [bounty] Add "关于发布BCHN版本0.21.2的公告" article

app/data/newsroom.json, blog/BCHN就11月份BCH升级的常见问题集锦.md
=> [bounty] Add "BCHN就11月份BCH升级的常见问题集锦" article

app/data/newsroom.json, blog/Bitcoin-Cash-Node客户端即将发布.md
=> [bounty] Add "Bitcoin Cash Node客户端即将发布" article

app/data/newsroom.json, blog/survey-june-2020.md
=> [bounty] Add "Bitcoin Cash Node Community Survey June 2020"

app/data/newsroom.json, blog/BCHN客户端首席维护者的工作汇报-2020-03-14.md
=> [bounty] Add "BCHN客户端首席维护者的工作汇报 (2020-03-14)" article

app/data/newsroom.json, blog/BCHN-lead-maintainer-report-2020-04-15.md
=> [bounty] Add "BCHN lead maintainer report 2020-04-15" article

app/data/newsroom.json, blog/BCHN首席开发者维护工作报告2020年4月15日.md
=> [bounty] Add "BCHN首席开发者维护工作报告2020年4月15日" article

app/data/newsroom.json, blog/Informe-del-responsable-de-mantenimiento-de-BCHN-15-04-2020.md
=> [bounty] Add "Informe del responsable de mantenimiento de BCHN 15-04-2020" article

app/data/newsroom.json, blog/BCHN 首席维护者报告-2020年6月15日.md
=> [bounty] Add "BCHN 首席维护者报告（2020年6月15日）article

app/members/calin-calianu.html, app/members/emergent-reasons.html, app/members/fernando-pelliccioni.html, app/members/freetrader.html, app/members/sickpig.html, app/team.html
Just some inconsistency in capitalization that could look more professional.
=> standardize style of team titles

app/data/newsroom.json, blog/Anúncio-d-BCHN-sobre-as-especificações-de-atualização-do-Bitcoin-Cash-BCH-Portuguêss.md, blog/BCHN-announcement-regarding-Bitcoin-Cash-(BCH)-upgrade-specifications.md
for: #110 
https://read.cash/@phabulu/anuncio-do-bchn-sobre-as-especificacoes-de-atualizacao-do-bitcoin-cash-bch-portugues-1d11944b
=> Add article BCHN-announcement-regarding-portugues

app/data/newsroom.json, blog/march-2020-survey.md, blog/março-2020-survey.md
for: #110 
Original Article: https://read.cash/@freetrader/bitcoin-cash-node-community-survey-march-2020-c23eb5a8
Translate article (Portuguese): https://read.cash/@phabulu/pesquisa-da-comunidade-bitcoin-cash-node-marco-de-2020-c3a8b7ee#o-que-acontece-com-seus-comentarios-apos-envia-los
=> Add Article Pesquisa da comunidade Bitcoin Cash Node - março de 2020

app/data/newsroom.json, blog/Announcing-Bitcoin-Cash-Node-v22-1-0.md, blog/BCHNv22_1_0版本发布公告.md
=> Add v22.1.0 release announcement articles: English and Chinese

app/data/newsroom.json, blog/BCHN-Financial-Report-2020-10-20.md
Add 2020-10-20 Financial Report
=> Add BCHN Financial Report 2020-10-20

app/download.html
Thanks to LeandroDiMarco for reporting the wrong link.
=> Fix v22.0.0 download link

app/members/tracy-chen.html, app/team.html
=> Add Tracy profile page

app/data/newsroom.json, blog/BCHN-Financial-Report-2021-02-08.md
Up to date to end of 2021-02-07.
=> Add BCHN Financial Report 2021-02-08

app/data/newsroom.json, blog/BCHN-Financial-Report-2020-12-05.md
No financial report left behind
=> Add BCHN Financial Report 2020-12-05

app/members/bigblockiftrue.html, app/team.html
Updates the description on team page and BigBlockIfTrue's profile page to
Maintainer and Developer
=> Update BigBlockIfTrue description to add Maintainer role

app/data/newsroom.json, blog/Announcing-Bitcoin-Cash-Node-v23-0-0.md, blog/BCHN-v23-0-0版本发布公告.md
Newsroom announcement articles for v23.0.0
=> Add v23.0.0 release announcement articles: English and Chinese

app/data/newsroom.json, blog/BCHN-Financial-Report-2021-04-17.md
Based on:
https://gitlab.com/bitcoin-cash-node/announcements/-/blob/master/20210417-bchn-financial-report.md
=> Add BCHN Financial Report 2021-04-17

app/templates/base.njk
Adds an upgrade banner to urge users to install v23.0.0.
Text is based on the one at bch.info, thank you very much <3
=> Enable May 15, 2021 upgrade banner

app/data/newsroom.json, blog/5-Awesome-Things-about-BCHN-v23_0_0_upgrade.md
Based on : https://read.cash/@bitcoincashnode/5-awesome-things-about-bchn-v2300-upgrade-287003a4
=> Add 5 Awesome Things about v23 article to newsroom

app/download.html
Thanks to matricz for noticing that this linked to the wrong release.
=> Fix v22.2.0 download link

app/data/newsroom.json, blog/BCHN-Financial-Report-2021-06-11.md
For review.
This report has already been published at these locations:
- https://gitlab.com/bitcoin-cash-node/announcements/-/blob/master/20210611-bchn-financial-report.md
- https://read.cash/@bitcoincashnode/bchn-financial-report-2021-06-11-7ba55cc6
=> Add BCHN Financial Report 2021-06-11 (English)

app/data/newsroom.json, blog/Announcing-Bitcoin-Cash-Node-v23-1-0.md
=> Add v23.1.0 release announcement articles: English

app/data/newsroom.json, blog/Announcing-Bitcoin-Cash-Node-v24-0-0.md
Based on:
https://gitlab.com/bitcoin-cash-node/announcements/-/blob/master/20211121_bchn_v24_0_0_release_announcement.md
Please review
=> Add v24.0.0 release announcement articles: English

app/data/newsroom.json, blog/BCHN-v24-0-0版本发布公告.md
v24.0.0 release announcement
thanks @imaginaryusername for translation
=> Add 24.0.0 chinese announcement

app/data/newsroom.json, blog/BCHN-Technical-Bulletin-2021-10-31.md
~~In Draft because I'm still checking / adjusting the Markdown formatting, since our website article MD has slightly different requirements from the input (heading depth etc)~~
~~So this is mainly for my own preview at this stage, but comments ARE welcome (if you spot something you think is wrong / badly laid out etc.)~~
Ready for others' review
=> Add the 2021-10-31 Tech Bulletin (LMDB P[reliminary Tech Report)

README.md, app/newsroom/Announcing-Bitcoin-Cash-Node-v24-0-0.html, app/newsroom/BCHN-Technical-Bulletin-2021-10-31.html, app/newsroom/BCHN-v24-0-0版本发布公告.html, package.json
This adds missing processed HTML files and standardizes start and build commands with npm scripts.
=> Add missing processed HTML files

app/data/newsroom.json, app/newsroom/BCHN-Financial-Report-2021-11-24.html, blog/BCHN-Financial-Report-2021-11-24.md
English version
Based on https://gitlab.com/bitcoin-cash-node/announcements/-/blob/master/20211124-bchn-financial-report.md
HTML added to forestall 404 problems with Preview.
=> Add Financial Report 2021-11-24
